### PR TITLE
Set up static page deployment on GitHub Pages

### PR DESCRIPTION
**Pull request by yongrenjie**
As title.

### CODE REVIEW

**Comment by martinfleis** [comment]
I know it is super preliminary but wanted to flag that it is bit broken in Safari on Mac.

**Comment by ciupava** [comment]
works in Chrome on Mac!

**Comment by ciupava** [comment]
Looks cool. My understanding is it has OS map as background. Are you considering having OSM data instead/also?

**Comment by ciupava** [comment]
Yep, but color scheme could be changed (depending on available layers, I believe, but not my expertise), I was thinking more about data sources and reproducibility in other areas. Definitely can be addressed later on.

**Comment by yongrenjie** [comment]
Thanks @martinfleis good to catch these super early! - Re map sources / colours: I'm figuring out tech first; but will definitely be looking at that in the near future when I've got something more developed. For OSM data I just need to swap out one line, and custom colour schemes can be done too.

https://github.com/alan-turing-institute/demoland-web/blob/806240d103742812cb175e813cf4dd1a2f1887eb/src/lib/Map.svelte#L12

**Pull request merged**
